#!/bin/bash
# role-utils.sh - 役割進化型ワークフロー用ユーティリティ
# 
# このファイルは worktree を使わないシンプルなワークフローをサポートします。
# すべての中間成果物は ./tmp/ ディレクトリに保存されます。

set -euo pipefail

# カラー定義
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
MAGENTA='\033[0;35m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# ログ関数
log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
log_warning() { echo -e "${YELLOW}[WARNING]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1" >&2; }
log_role() { echo -e "${MAGENTA}[ROLE]${NC} $1"; }

# 現在の役割を保存する変数
CURRENT_ROLE=""

# tmpディレクトリの確保
ensure_tmp_dir() {
    if [[ ! -d "./tmp" ]]; then
        mkdir -p ./tmp
        log_success "Created ./tmp directory"
    fi
}

# 役割の切り替え
switch_role() {
    local new_role="$1"
    local description="${2:-}"
    
    CURRENT_ROLE="$new_role"
    
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    log_role "🎭 Switching to $new_role mode"
    if [[ -n "$description" ]]; then
        echo -e "${CYAN}$description${NC}"
    fi
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
}

# 成果物の保存（./tmp/に統一）
save_artifact() {
    local role="$1"
    local content="$2"
    local timestamp=$(date +%Y%m%d-%H%M%S)
    local role_lower=$(echo "$role" | tr '[:upper:]' '[:lower:]')
    local filepath="./tmp/${timestamp}-${role_lower}-report.md"
    
    ensure_tmp_dir
    
    # 内容を保存
    echo "$content" > "$filepath"
    log_success "Saved: $filepath"
    
    # 最新のリンクも作成（参照しやすくするため）
    ln -sf "$(basename "$filepath")" "./tmp/latest-${role_lower}-report.md"
    log_info "Created link: ./tmp/latest-${role_lower}-report.md"
    
    # ファイルパスを返す
    echo "$filepath"
}

# 前の役割の成果物を読み込み
load_previous_artifact() {
    local role="$1"
    local role_lower=$(echo "$role" | tr '[:upper:]' '[:lower:]')
    local filepath="./tmp/latest-${role_lower}-report.md"
    
    if [[ -f "$filepath" ]]; then
        log_info "Loading previous $role artifact..."
        bat --style=plain "$filepath"
    else
        log_warning "No previous $role artifact found"
        echo ""
    fi
}

# 最新の成果物パスを取得
get_latest_artifact_path() {
    local role="$1"
    local role_lower=$(echo "$role" | tr '[:upper:]' '[:lower:]')
    echo "./tmp/latest-${role_lower}-report.md"
}

# プログレス表示
show_progress() {
    local current_step="$1"
    local total_steps="${2:-5}"
    local task_description="${3:-}"
    
    local progress=$((current_step * 100 / total_steps))
    local filled=$((progress / 10))
    local empty=$((10 - filled))
    
    echo ""
    echo -e "${CYAN}Task:${NC} $task_description"
    echo -n "Progress ["
    printf "%${filled}s" | tr ' ' '='
    printf "%${empty}s" | tr ' ' '-'
    echo "] ${progress}%"
    echo ""
}

# タスクサマリーの生成
generate_task_summary() {
    local task_description="$1"
    local timestamp=$(date +%Y%m%d-%H%M%S)
    local summary_path="./tmp/${timestamp}-task-summary.md"
    
    ensure_tmp_dir
    
    # 生成された成果物をリスト
    local artifacts=$(eza -la ./tmp/*-report.md 2>/dev/null | tail -10 || echo "No artifacts found")
    
    cat > "$summary_path" << EOF
# Task Summary

**Task**: $task_description  
**Date**: $(date)  
**Generated by**: Role Evolution Workflow

## Artifacts Generated

\`\`\`
$artifacts
\`\`\`

## Roles Executed

$(eza ./tmp/latest-*-report.md 2>/dev/null | while read -r file; do
    if [[ -f "$file" ]]; then
        role=$(basename "$file" | sed 's/latest-\(.*\)-report.md/\1/')
        echo "- ✅ ${role^}"
    fi
done || echo "- No roles executed yet")

## Next Steps

1. Review all reports in \`./tmp/\`
2. Commit changes if satisfied
3. Clean up old artifacts: \`cleanup_tmp 7\`

## Quick Access

- Explorer Report: \`./tmp/latest-explorer-report.md\`
- Analysis Report: \`./tmp/latest-analysis-report.md\`
- Design Document: \`./tmp/latest-design-report.md\`
- Implementation Log: \`./tmp/latest-implementation-report.md\`
- Review Report: \`./tmp/latest-review-report.md\`
EOF
    
    log_success "Task summary saved: $summary_path"
    
    # 最新のサマリーへのリンクも作成
    ln -sf "$(basename "$summary_path")" "./tmp/latest-task-summary.md"
}

# ./tmp/のクリーンアップ（オプション）
cleanup_tmp() {
    local days_old="${1:-7}"
    
    log_info "Cleaning up files older than $days_old days in ./tmp/..."
    
    local count=0
    while IFS= read -r file; do
        if [[ -f "$file" ]]; then
            log_info "Removing: $file"
            rm -f "$file"
            ((count++))
        fi
    done < <(find ./tmp -name "*-report.md" -o -name "*-summary.md" -mtime +$days_old 2>/dev/null || true)
    
    if [[ $count -eq 0 ]]; then
        log_info "No old files found"
    else
        log_success "Cleaned up $count old files"
    fi
}

# 役割の説明を表示
show_role_description() {
    local role="$1"
    
    case "$role" in
        "Explorer")
            echo "🔍 調査・探索: 既存コードの理解、要件の明確化、制約の特定"
            ;;
        "Analyst")
            echo "📊 分析・評価: 影響範囲の分析、リスク評価、実装戦略の検討"
            ;;
        "Designer")
            echo "🎨 設計・計画: アーキテクチャ設計、インターフェース定義、テスト戦略"
            ;;
        "Developer")
            echo "💻 実装・開発: コード実装、ユニットテスト作成、段階的コミット"
            ;;
        "Reviewer")
            echo "✅ レビュー・品質確認: コードレビュー、テスト実行、ドキュメント整備"
            ;;
        *)
            echo "❓ Unknown role: $role"
            ;;
    esac
}

# インタラクティブな役割選択
select_next_role() {
    local current_role="${1:-}"
    
    echo ""
    log_info "Select next role:"
    echo "1) Explorer  - 調査・探索"
    echo "2) Analyst   - 分析・評価"
    echo "3) Designer  - 設計・計画"
    echo "4) Developer - 実装・開発"
    echo "5) Reviewer  - レビュー・品質確認"
    echo "6) Exit      - 終了"
    echo ""
    
    read -p "Choice (1-6): " choice
    
    case $choice in
        1) echo "Explorer" ;;
        2) echo "Analyst" ;;
        3) echo "Designer" ;;
        4) echo "Developer" ;;
        5) echo "Reviewer" ;;
        6) echo "Exit" ;;
        *) echo "Invalid" ;;
    esac
}

# エラーハンドリング
handle_error() {
    local exit_code=$1
    local error_msg=$2
    
    log_error "$error_msg (Exit code: $exit_code)"
    
    # エラーレポートを./tmp/に保存
    local timestamp=$(date +%Y%m%d-%H%M%S)
    local error_report="./tmp/${timestamp}-error-report.md"
    
    ensure_tmp_dir
    cat > "$error_report" << EOF
# Error Report

**Time**: $(date)  
**Exit Code**: $exit_code  
**Error**: $error_msg  
**Current Role**: ${CURRENT_ROLE:-Unknown}

## Stack Trace
$(caller)

## Suggestions
- Check the error message above
- Review recent changes
- Run with debug mode: \`bash -x\`
EOF
    
    log_error "Error report saved: $error_report"
    
    # テストモードでなければ終了
    if [[ "${TEST_MODE:-false}" != "true" ]]; then
        exit "$exit_code"
    fi
}

# 環境検証（簡素化版）
verify_environment() {
    log_info "Verifying environment..."
    
    # Git確認
    if ! command -v git &> /dev/null; then
        handle_error 1 "Git is not installed"
    fi
    
    # 現在のディレクトリがgitリポジトリか確認
    if ! git rev-parse --is-inside-work-tree &> /dev/null; then
        handle_error 1 "Not inside a git repository"
    fi
    
    log_success "Environment verification passed"
}

# 使用統計の表示
show_statistics() {
    ensure_tmp_dir
    
    echo ""
    echo "📊 Workflow Statistics"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    
    # 各役割の成果物数をカウント
    for role in explorer analyst designer developer reviewer; do
        local count=$(eza ./tmp/*-${role}-report.md 2>/dev/null | wc -l || echo "0")
        printf "%-12s: %3d artifacts\n" "${role^}" "$count"
    done
    
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    
    # 合計サイズ
    local total_size=$(du -sh ./tmp 2>/dev/null | cut -f1 || echo "0")
    echo "Total size: $total_size"
}

# エクスポート
export -f log_info log_success log_warning log_error log_role
export -f ensure_tmp_dir switch_role save_artifact load_previous_artifact
export -f get_latest_artifact_path show_progress generate_task_summary
export -f cleanup_tmp show_role_description select_next_role
export -f handle_error verify_environment show_statistics
export CURRENT_ROLE

# スクリプトが直接実行された場合のヘルプ表示
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    echo "role-utils.sh - Role Evolution Workflow Utilities"
    echo ""
    echo "This script provides utilities for the role-based workflow."
    echo "It should be sourced in other scripts:"
    echo ""
    echo "  source .klaude/scripts/role-utils.sh"
    echo ""
    echo "Available functions:"
    echo "  - switch_role <role> [description]"
    echo "  - save_artifact <role> <content>"
    echo "  - load_previous_artifact <role>"
    echo "  - show_progress <current> <total> [task]"
    echo "  - generate_task_summary <task_description>"
    echo "  - cleanup_tmp [days_old]"
    echo "  - show_statistics"
    echo ""
fi