-- tests/test_checkbox_spec.lua
-- Layer 1: チェックボックスの状態サイクル + バッファ操作テスト

local helpers = require("tests.helpers")

describe("checkbox", function()
  local checkbox

  before_each(function()
    checkbox = require("vw.checkbox")
  end)

  describe("toggle_as_task", function()
    it("プレーンテキストに - [ ] を追加する", function()
      local buf = helpers.create_buf({ "タスク内容" })
      vim.api.nvim_win_set_cursor(0, { 1, 0 })
      checkbox.toggle_as_task()
      local lines = helpers.get_buf_lines(buf)
      assert.are.equal("- [ ] タスク内容", lines[1])
      helpers.cleanup_buf(buf)
    end)

    it("- 項目 を - [ ] 項目 に変換する", function()
      local buf = helpers.create_buf({ "- 項目" })
      vim.api.nvim_win_set_cursor(0, { 1, 0 })
      checkbox.toggle_as_task()
      local lines = helpers.get_buf_lines(buf)
      assert.are.equal("- [ ] 項目", lines[1])
      helpers.cleanup_buf(buf)
    end)

    it("- [ ] 項目 からチェックボックスを削除する", function()
      local buf = helpers.create_buf({ "- [ ] 項目" })
      vim.api.nvim_win_set_cursor(0, { 1, 0 })
      checkbox.toggle_as_task()
      local lines = helpers.get_buf_lines(buf)
      assert.are.equal("項目", lines[1])
      helpers.cleanup_buf(buf)
    end)

    it("インデント付きでも動作する", function()
      local buf = helpers.create_buf({ "  テスト" })
      vim.api.nvim_win_set_cursor(0, { 1, 0 })
      checkbox.toggle_as_task()
      local lines = helpers.get_buf_lines(buf)
      assert.are.equal("  - [ ] テスト", lines[1])
      helpers.cleanup_buf(buf)
    end)
  end)

  describe("toggle_checkbox_state", function()
    it("[ ] → [>] (未着手→実行中)", function()
      local buf = helpers.create_buf({ "- [ ] タスク" })
      vim.api.nvim_win_set_cursor(0, { 1, 0 })
      checkbox.toggle_checkbox_state()
      local lines = helpers.get_buf_lines(buf)
      assert.are.equal("- [>] タスク", lines[1])
      helpers.cleanup_buf(buf)
    end)

    it("[>] → [@] (実行中→AI委譲)", function()
      local buf = helpers.create_buf({ "- [>] タスク" })
      vim.api.nvim_win_set_cursor(0, { 1, 0 })
      checkbox.toggle_checkbox_state()
      local lines = helpers.get_buf_lines(buf)
      assert.are.equal("- [@] タスク", lines[1])
      helpers.cleanup_buf(buf)
    end)

    it("[@] → [v] (AI委譲→成功)", function()
      local buf = helpers.create_buf({ "- [@] タスク" })
      vim.api.nvim_win_set_cursor(0, { 1, 0 })
      checkbox.toggle_checkbox_state()
      local lines = helpers.get_buf_lines(buf)
      assert.are.equal("- [v] タスク", lines[1])
      helpers.cleanup_buf(buf)
    end)

    it("[v] → [/] (成功→中断)", function()
      local buf = helpers.create_buf({ "- [v] タスク" })
      vim.api.nvim_win_set_cursor(0, { 1, 0 })
      checkbox.toggle_checkbox_state()
      local lines = helpers.get_buf_lines(buf)
      assert.are.equal("- [/] タスク", lines[1])
      helpers.cleanup_buf(buf)
    end)

    it("[/] → [x] (中断→失敗)", function()
      local buf = helpers.create_buf({ "- [/] タスク" })
      vim.api.nvim_win_set_cursor(0, { 1, 0 })
      checkbox.toggle_checkbox_state()
      local lines = helpers.get_buf_lines(buf)
      assert.are.equal("- [x] タスク", lines[1])
      helpers.cleanup_buf(buf)
    end)

    it("[x] → [ ] (失敗→未着手) — フルサイクル", function()
      local buf = helpers.create_buf({ "- [x] タスク" })
      vim.api.nvim_win_set_cursor(0, { 1, 0 })
      checkbox.toggle_checkbox_state()
      local lines = helpers.get_buf_lines(buf)
      assert.are.equal("- [ ] タスク", lines[1])
      helpers.cleanup_buf(buf)
    end)

    it("チェックボックスがない行は変更しない", function()
      local buf = helpers.create_buf({ "普通のテキスト" })
      vim.api.nvim_win_set_cursor(0, { 1, 0 })
      checkbox.toggle_checkbox_state()
      local lines = helpers.get_buf_lines(buf)
      assert.are.equal("普通のテキスト", lines[1])
      helpers.cleanup_buf(buf)
    end)
  end)
end)
