-- tests/test_header_spec.lua
-- Layer 1: ヘッダー挿入・削除のロジックテスト

local helpers = require("tests.helpers")

describe("header", function()
  local markdown_helper

  before_each(function()
    markdown_helper = require("user-plugins.markdown-helper")
  end)

  describe("insert_markdown_header", function()
    it("プレーンテキストに # を追加する", function()
      local buf = helpers.create_buf({ "タイトル" })
      vim.api.nvim_win_set_cursor(0, { 1, 0 })
      markdown_helper.insert_markdown_header(1)
      local lines = helpers.get_buf_lines(buf)
      assert.are.equal("# タイトル", lines[1])
      helpers.cleanup_buf(buf)
    end)

    it("H2 ヘッダーを挿入する", function()
      local buf = helpers.create_buf({ "タイトル" })
      vim.api.nvim_win_set_cursor(0, { 1, 0 })
      markdown_helper.insert_markdown_header(2)
      local lines = helpers.get_buf_lines(buf)
      assert.are.equal("## タイトル", lines[1])
      helpers.cleanup_buf(buf)
    end)

    it("既存の H1 を H3 に置き換える", function()
      local buf = helpers.create_buf({ "# タイトル" })
      vim.api.nvim_win_set_cursor(0, { 1, 0 })
      markdown_helper.insert_markdown_header(3)
      local lines = helpers.get_buf_lines(buf)
      assert.are.equal("### タイトル", lines[1])
      helpers.cleanup_buf(buf)
    end)

    it("H6 まで対応する", function()
      local buf = helpers.create_buf({ "見出し" })
      vim.api.nvim_win_set_cursor(0, { 1, 0 })
      markdown_helper.insert_markdown_header(6)
      local lines = helpers.get_buf_lines(buf)
      assert.are.equal("###### 見出し", lines[1])
      helpers.cleanup_buf(buf)
    end)
  end)

  describe("remove_markdown_header", function()
    it("ヘッダーを削除する", function()
      local buf = helpers.create_buf({ "## タイトル" })
      vim.api.nvim_win_set_cursor(0, { 1, 0 })
      markdown_helper.remove_markdown_header()
      local lines = helpers.get_buf_lines(buf)
      assert.are.equal("タイトル", lines[1])
      helpers.cleanup_buf(buf)
    end)

    it("ヘッダーがない行は変更しない", function()
      local buf = helpers.create_buf({ "普通のテキスト" })
      vim.api.nvim_win_set_cursor(0, { 1, 0 })
      markdown_helper.remove_markdown_header()
      local lines = helpers.get_buf_lines(buf)
      assert.are.equal("普通のテキスト", lines[1])
      helpers.cleanup_buf(buf)
    end)
  end)
end)
